- name: install git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: yes
  when: ansible_distribution != "CentOS"
  become: true

- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_distribution != "CentOS"
  become: true

- name: install cowsay
  ansible.builtin.apt:
    name: cowsay
    state: present
    update_cache: yes
  become: true