- hosts: webservers
  vars:
    app_dir: app

  roles:
    - role: mrlesmithjr.nodejs

    - role: kevincoakley.postgres

  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution != "CentOS"
      become: true

    - name: git clone app
      ansible.builtin.git:
        repo: https://github.com/hexlet-components/js-fastify-blog
        dest: '/{{ app_dir }}'

    - name: set env
      ansible.builtin.copy:
        src: files/.env
        dest: '/{{ app_dir }}/.env'
      become: true

    - name: npm install
      community.general.npm:
        path: '/{{ app_dir }}'

    - name: setup app
      shell: make setup
      args:
        chdir: '/{{ app_dir }}'

    - name: start app
      shell: make start
      args:
        chdir: '/{{ app_dir }}'